[user]
email = "m@andreym.com"
name = "Andrey Moor"

[signing]
behaviour = "own"
backend = "gpg"

[aliases]
b = ["branch"]
n = ["new"]

[template-aliases]
"format_timestamp(timestamp)" = "timestamp.ago()"

[ui]
default-command = "log"
